# Generated by Django 3.2.3 on 2021-06-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
